### ISSUE TITLE
latest version give error when running yt-dlp --version

### ISSUE THREAD

**Issue by TeLLie** [bitwiseworks/python-os2#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TeLLie** [comment]
Hi
When running the latest python version i notice when running python yt-dlp --version gives here a erros like: 

C:\Home\.local\share\media-downloader\bin>python yt-dlp --version
Traceback (most recent call last):
  File "C:/Home/.local/share/media-downloader/bin/yt-dlp/yt_dlp/__init__.py", line 2, in <module>
  File "C:/USR/lib/python3.9/contextvars.py", line 1, in <module>
    from _contextvars import Context, ContextVar, Token, copy_context
ImportError: dlopen rc=123 extra=C:\USR\LIB\PYTHON3.9\LIB-DYNLOAD\_CONTEXTVARS.PYD

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/USR/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:/USR/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:/Home/.local/share/media-downloader/bin/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:/Home/.local/share/media-downloader/bin/yt-dlp/yt_dlp/__init__.py", line 4, in <module>
Exception: You are using an unsupported version of Python. Only Python versions 3.7 and above are supported by yt-dlp



While previous version says:

C:\Home\.local\share\media-downloader\bin>K:\usr\bin\python yt-dlp --version
2023.09.24

**Comment by TeLLie** [comment]
this can be closed as it turns out my usr die had no symlinks when I copy from a other laptop...
