### ISSUE TITLE
os.rmdir fails with Errno 16

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/python-os2#5]
The following test
```python
import os
try:
 os.rmdir('1')
except:
 pass
os.mkdir('1')
os.chdir('1')
os.rmdir('../1')
```
fails like this (both in python2 and python3):
```
D:>python2.7 rmdir.py
Traceback (most recent call last):
  File "rmdir.py", line 8, in <module>
    os.rmdir('../1')
OSError: [Errno 16] Resource busy: '../1'

D:>python3.9 rmdir.py
Traceback (most recent call last):
  File "D:/Coding/Tests/python/rmdir.py", line 8, in <module>
    os.rmdir('../1')
OSError: [Errno 16] Resource busy: '../1'
```
Which is expected because on OS/2 you can't delete a directory which is the current one (on Linux and BSD this is allowed and the test succeeds). A solution is to just `chdir("..")` before calling the underlying Posix `rmdir` function in the implementation of `os.rmdir`. It will always work provided we are not deleting the root drive (which is impossible anyway).

**Comment by dmik** [comment]
The real life example of this problem is Chromium's SQLite amalgamation script:

https://github.com/bitwiseworks/qtwebengine-chromium-os2/blob/51c5dce228e04096d8450174c8bbd4d6586b0c26/chromium/third_party/sqlite/scripts/generate_amalgamation.py#L218

They call `rmtree` there which eventually calls `rmdir` on a temporary directory which is the current one (changed to with `chdir` in the very beginning).
