### ISSUE TITLE
Problems with subprocess.py

### ISSUE THREAD

**Issue by psmedley** [bitwiseworks/python-os2#9]
**Describe the bug**
Trying to build QtWebEngine 6.3.2 (which moved to using python 3.x instead of python 2.x), I'm seeing the following error:
`Traceback (most recent call last):
  File "U:/dev/qt6-webengine-os2-6.3.x/build/src/core/Release/i386/../../../../../src/3rdparty/chromium/third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 302, in <module>
    sys.exit(main())
  File "U:/dev/qt6-webengine-os2-6.3.x/build/src/core/Release/i386/../../../../../src/3rdparty/chromium/third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 281, in main
    found_errors, stderr = runTsc(
  File "U:/dev/qt6-webengine-os2-6.3.x/build/src/core/Release/i386/../../../../../src/3rdparty/chromium/third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 56, in runTsc
    stdout, stderr = process.communicate()
  File "C:/USR/lib/python3.9/subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:/USR/lib/python3.9/subprocess.py", line 2109, in _communicate
    stdout = b''.join(stdout)
TypeError: sequence item 0: expected a bytes-like object, str found
`
**To Reproduce**
I will try and distill this down to a simple testcase.

**Expected behavior**
The command completes successfully. There are numerous matches of the final error - for example https://stackoverflow.com/questions/54863236/typeerror-sequence-item-0-expected-a-bytes-like-object-str-found

**Comment by psmedley** [comment]
Reading some more, the problem may be that node is producing binary output on stdout, will check.

**Comment by psmedley** [comment]
OK - the fix seems too be to copy some code from the windows version of _communicate

Adding:
`                # All data exchanged.  Translate lists into strings.
                stdout = stdout[0] if stdout else None
                stderr = stderr[0] if stderr else None
`
(from https://github.com/bitwiseworks/python-os2/blob/master/Lib/subprocess.py#L1545)

to https://github.com/bitwiseworks/python-os2/blob/master/Lib/subprocess.py#L2025 seems to resolve (based on the initial failing code).

**Comment by SilvanScherrer** [comment]
fixed with the above commit

**Comment by dmik** [comment]
This fix doesn't seem to be correct. As opposed to Windows, file I/O buffers in Posix are bytes, not strings. And OS/2 follows the Posix codepath closely. For this very simple test:

```py
import subprocess
print ("[",subprocess.Popen (['cmd', '/c', 'ver'],
  stdout = subprocess.PIPE, stderr = subprocess.PIPE).communicate()[0],"]")
```

the above fix fails like this:

```
D:>python3.9.exe t.py
Traceback (most recent call last):
  File "D:/Tests/python/#9/t.py", line 2, in <module>
    print ("[",subprocess.Popen (['cmd', '/c', 'ver'], stdout = subprocess.PIPE, stderr = subprocess.PIPE).communicate()[0],"]")
  File "C:/USR/lib/python3.9/subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:/USR/lib/python3.9/subprocess.py", line 2028, in _communicate
    stdout = ''.join(stdout)
TypeError: sequence item 0: expected str instance, bytes found
```

While the version with the above commit reverted works flawlessly:

```
D:>python3.9.exe t.py
[ b'\r\nThe Operating System/2 Version is 4.50 \r\n' ]
```

**Comment by dmik** [comment]
I've pushed a revert as we also don't want to move new line handling to the non-OS/2 part of _communicate (OS/2 needs that as well). As for the original problem, I will ask to boil it down to the simplest test case that shows it. I couldn't find one so far. May be we should use a different fix then.

Leaving this open till more testing is done.

**Comment by psmedley** [comment]
I may have a testcase somewhere. Assuming QtWebEngine 5.15.x uses python3 - you'll come across this when invoking node.exe in building it

**Comment by dmik** [comment]
It is surely something else. You may see for yourself that the above fix breaks the very basic example of `subprocess` usage. So it would be really nice if you could find your test case. As building QtWebEngine isn't going to happen very soon here.

**Comment by psmedley** [comment]
OK will see what I can come up with - from memory it was a simple case that invoked node.exe. To be clear, I'm talking about my fix in https://github.com/psmedley/python-os2/commit/fd8f24890e59a8e086226e2ef0098ff66e8d4eb0 not Silvan's fix. With my fix, your testcase in https://github.com/bitwiseworks/python-os2/issues/9#issuecomment-1603210884 works.

**Comment by dmik** [comment]
I'm sorry but that can't be true. With your fix

```py
                # All data exchanged.  Translate lists into strings.
                stdout = stdout[0] if stdout else None
                stderr = stderr[0] if stderr else None
```

applied to the current tree at line 2026 it doesn't work here either:

```
D:>python3.9.exe t.py
Traceback (most recent call last):
  File "D:/Tests/python/#9/t.py", line 2, in <module>
    print ("[",subprocess.Popen (['cmd', '/c', 'ver'],
  File "C:/USR/lib/python3.9/subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:/USR/lib/python3.9/subprocess.py", line 2113, in _communicate
    stdout = b''.join(stdout)
TypeError: sequence item 0: expected a bytes-like object, int found
```

Which is expected because the common code part does this after the OS/2 part:

```py
            # All data exchanged.  Translate lists into strings.
            if stdout is not None:
                stdout = b''.join(stdout)
            if stderr is not None:
                stderr = b''.join(stderr)
```

The first snippet (yours, the one you borrowed from the Win32 code) turns the array of byte strings into a single byte string using the first element of that array. This is based on the assumption that the stdout/stderr thread will read out everything in one go. The second snippet (the Posix approach) assumes that there might be multiple reads and just joins them all into a single byte string. However, since your snippet has already converted the array into a single byte string, it cannot be a valid argument for `bytes.join()` (it requires an iterable that returns byte strings, not bytes and not anything else). Hence the above error.

So it should either be the first snippet or the second one, but not both. While on OS/2 there should also be only one array entry anyway (all data is read out in one go before the underlying read call returns, and then the stream is closed), any of these snippets will give equal results in the end. I prefer to keep the Posix one just to make the code simpler (it's a shared part).

I think we may close this ticket as with my fix (already pushed) I see no further issues here. Please feel free to reopen if you find one.

**Comment by dmik** [comment]
I got a test case from Elbert and now I know what's wrong. The type of objects for stdin/out/err actually depends on the `text` parameter to various `subprocess.Popen` APIs (and also on `encoding` and some others that indirectly imply `text` = `True`). If text mode is on, then all the involved sequences are strings. If it is off (which is the default) then they are byte arrays.

So'm if I modify my test case from https://github.com/bitwiseworks/python-os2/issues/9#issuecomment-1603210884 by adding `text = True` to `subprocess.Popen`, I'm able to easily reproduce the problem, i.e. this exception:

```
Traceback (most recent call last):
  File "D:/Tests/python/#9/t4.py", line 2, in <module>
    print ("[",subprocess.Popen (['cmd', '/c', 'ver'], text = True,
  File "C:/USR/lib/python3.9/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:/USR/lib/python3.9/subprocess.py", line 2114, in _communicate
    stdout = b''.join(stdout)
TypeError: sequence item 0: expected a bytes-like object, str found
```

Just the same as Paul gets.

**Comment by dmik** [comment]
All cases work fine here now. Note that the resulting commit is sorta mix of what Paul and Silvan did. We don't need to convert bytes to strings as Posix does because on Posix the data is always read directly from file descriptors as bytes but this is NOT the case on OS/2 in text mode. In this case, the code uses a `io.TextIOWrapper` wrapper just like Win32 does (note that this wrapper also converts `\r\n` to just `\n` so no explicit conversion like on Posix is needed either). So what Silvan did by hiding this Posix code is right.

What about the first part of the fix, the Paul's one is the correct one (and it's taken right from Win32 code).
